"""empty message

Revision ID: 07302472424c
Revises: 56e5d374c465
Create Date: 2021-10-28 02:00:14.460317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07302472424c'
down_revision = '56e5d374c465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'owner_id')
    # ### end Alembic commands ###
