"""empty message

Revision ID: 63566dc0fd9e
Revises: cfb6f34ae807
Create Date: 2021-10-20 18:38:31.104233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63566dc0fd9e'
down_revision = 'cfb6f34ae807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('seat_1', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tables', 'users', ['seat_1'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_column('tables', 'seat_1')
    # ### end Alembic commands ###
