"""empty message

Revision ID: 0203e9f6246e
Revises: 2b6c9facdc34
Create Date: 2021-10-20 16:22:40.983632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0203e9f6246e'
down_revision = '2b6c9facdc34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamelogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gameId', sa.Integer(), nullable=True),
    sa.Column('turn', sa.Integer(), nullable=True),
    sa.Column('actingplayer', sa.Integer(), nullable=True),
    sa.Column('move', sa.String(length=255), nullable=True),
    sa.Column('resolution', sa.String(length=255), nullable=True),
    sa.Column('bet', sa.Integer(), nullable=True),
    sa.Column('currentPot', sa.Integer(), nullable=True),
    sa.Column('player1_id', sa.Integer(), nullable=True),
    sa.Column('player1_simoleans', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('player2_simoleans', sa.Integer(), nullable=True),
    sa.Column('player3_id', sa.Integer(), nullable=True),
    sa.Column('player3_simoleans', sa.Integer(), nullable=True),
    sa.Column('player4_id', sa.Integer(), nullable=True),
    sa.Column('player4_simoleans', sa.Integer(), nullable=True),
    sa.Column('player5_id', sa.Integer(), nullable=True),
    sa.Column('player5_simoleans', sa.Integer(), nullable=True),
    sa.Column('player6_id', sa.Integer(), nullable=True),
    sa.Column('player6_simoleans', sa.Integer(), nullable=True),
    sa.Column('player7_id', sa.Integer(), nullable=True),
    sa.Column('player7_simoleans', sa.Integer(), nullable=True),
    sa.Column('player8_id', sa.Integer(), nullable=True),
    sa.Column('player8_simoleans', sa.Integer(), nullable=True),
    sa.Column('player9_id', sa.Integer(), nullable=True),
    sa.Column('player9_simoleans', sa.Integer(), nullable=True),
    sa.Column('player10_id', sa.Integer(), nullable=True),
    sa.Column('player10_simoleans', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actingplayer'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player10_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player3_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player4_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player5_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player6_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player7_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player8_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player9_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tableName', sa.String(length=255), nullable=True),
    sa.Column('seat1', sa.Integer(), nullable=True),
    sa.Column('seat2', sa.Integer(), nullable=True),
    sa.Column('seat3', sa.Integer(), nullable=True),
    sa.Column('seat4', sa.Integer(), nullable=True),
    sa.Column('seat5', sa.Integer(), nullable=True),
    sa.Column('seat6', sa.Integer(), nullable=True),
    sa.Column('seat7', sa.Integer(), nullable=True),
    sa.Column('seat8', sa.Integer(), nullable=True),
    sa.Column('seat9', sa.Integer(), nullable=True),
    sa.Column('seat10', sa.Integer(), nullable=True),
    sa.Column('currentTurn', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seat1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seat10'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seat2'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seat3'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seat4'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seat5'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seat6'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seat7'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seat8'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seat9'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tables')
    op.drop_table('gamelogs')
    # ### end Alembic commands ###
