"""empty message

Revision ID: 3c2c7b17a19f
Revises: 63566dc0fd9e
Create Date: 2021-10-20 18:47:14.062719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2c7b17a19f'
down_revision = '63566dc0fd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('seat_2', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tables', 'users', ['seat_2'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_column('tables', 'seat_2')
    # ### end Alembic commands ###
