"""empty message

Revision ID: cfb6f34ae807
Revises: 0ba1a94489af
Create Date: 2021-10-20 17:50:23.975998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfb6f34ae807'
down_revision = '0ba1a94489af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gamelogs_player6_id_fkey', 'gamelogs', type_='foreignkey')
    op.drop_constraint('gamelogs_player1_id_fkey', 'gamelogs', type_='foreignkey')
    op.drop_constraint('gamelogs_player5_id_fkey', 'gamelogs', type_='foreignkey')
    op.drop_constraint('gamelogs_player10_id_fkey', 'gamelogs', type_='foreignkey')
    op.drop_constraint('gamelogs_player4_id_fkey', 'gamelogs', type_='foreignkey')
    op.drop_constraint('gamelogs_actingplayer_fkey', 'gamelogs', type_='foreignkey')
    op.drop_constraint('gamelogs_player8_id_fkey', 'gamelogs', type_='foreignkey')
    op.drop_constraint('gamelogs_player3_id_fkey', 'gamelogs', type_='foreignkey')
    op.drop_constraint('gamelogs_player2_id_fkey', 'gamelogs', type_='foreignkey')
    op.drop_constraint('gamelogs_player9_id_fkey', 'gamelogs', type_='foreignkey')
    op.drop_constraint('gamelogs_player7_id_fkey', 'gamelogs', type_='foreignkey')
    op.drop_column('gamelogs', 'player1_simoleans')
    op.drop_column('gamelogs', 'player10_id')
    op.drop_column('gamelogs', 'player8_id')
    op.drop_column('gamelogs', 'actingplayer')
    op.drop_column('gamelogs', 'player3_simoleans')
    op.drop_column('gamelogs', 'player9_simoleans')
    op.drop_column('gamelogs', 'player3_id')
    op.drop_column('gamelogs', 'player5_simoleans')
    op.drop_column('gamelogs', 'player6_simoleans')
    op.drop_column('gamelogs', 'player5_id')
    op.drop_column('gamelogs', 'player7_id')
    op.drop_column('gamelogs', 'player4_simoleans')
    op.drop_column('gamelogs', 'player4_id')
    op.drop_column('gamelogs', 'created_at')
    op.drop_column('gamelogs', 'player6_id')
    op.drop_column('gamelogs', 'player8_simoleans')
    op.drop_column('gamelogs', 'player2_id')
    op.drop_column('gamelogs', 'player1_id')
    op.drop_column('gamelogs', 'player7_simoleans')
    op.drop_column('gamelogs', 'player2_simoleans')
    op.drop_column('gamelogs', 'player10_simoleans')
    op.drop_column('gamelogs', 'player9_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamelogs', sa.Column('player9_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player10_simoleans', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player2_simoleans', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player7_simoleans', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player8_simoleans', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player6_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player4_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player4_simoleans', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player7_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player5_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player6_simoleans', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player5_simoleans', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player3_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player9_simoleans', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player3_simoleans', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('actingplayer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player8_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player10_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gamelogs', sa.Column('player1_simoleans', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('gamelogs_player7_id_fkey', 'gamelogs', 'users', ['player7_id'], ['id'])
    op.create_foreign_key('gamelogs_player9_id_fkey', 'gamelogs', 'users', ['player9_id'], ['id'])
    op.create_foreign_key('gamelogs_player2_id_fkey', 'gamelogs', 'users', ['player2_id'], ['id'])
    op.create_foreign_key('gamelogs_player3_id_fkey', 'gamelogs', 'users', ['player3_id'], ['id'])
    op.create_foreign_key('gamelogs_player8_id_fkey', 'gamelogs', 'users', ['player8_id'], ['id'])
    op.create_foreign_key('gamelogs_actingplayer_fkey', 'gamelogs', 'users', ['actingplayer'], ['id'])
    op.create_foreign_key('gamelogs_player4_id_fkey', 'gamelogs', 'users', ['player4_id'], ['id'])
    op.create_foreign_key('gamelogs_player10_id_fkey', 'gamelogs', 'users', ['player10_id'], ['id'])
    op.create_foreign_key('gamelogs_player5_id_fkey', 'gamelogs', 'users', ['player5_id'], ['id'])
    op.create_foreign_key('gamelogs_player1_id_fkey', 'gamelogs', 'users', ['player1_id'], ['id'])
    op.create_foreign_key('gamelogs_player6_id_fkey', 'gamelogs', 'users', ['player6_id'], ['id'])
    # ### end Alembic commands ###
