"""empty message

Revision ID: 0ba1a94489af
Revises: 0203e9f6246e
Create Date: 2021-10-20 17:28:57.361104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba1a94489af'
down_revision = '0203e9f6246e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tables_seat9_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat5_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat1_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat8_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat3_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat2_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat7_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat6_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat4_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat10_fkey', 'tables', type_='foreignkey')
    op.drop_column('tables', 'seat8')
    op.drop_column('tables', 'seat6')
    op.drop_column('tables', 'seat7')
    op.drop_column('tables', 'seat1')
    op.drop_column('tables', 'seat9')
    op.drop_column('tables', 'seat4')
    op.drop_column('tables', 'seat5')
    op.drop_column('tables', 'seat10')
    op.drop_column('tables', 'seat3')
    op.drop_column('tables', 'seat2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('seat2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat10', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat5', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat4', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat9', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat7', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat6', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat8', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tables_seat10_fkey', 'tables', 'users', ['seat10'], ['id'])
    op.create_foreign_key('tables_seat4_fkey', 'tables', 'users', ['seat4'], ['id'])
    op.create_foreign_key('tables_seat6_fkey', 'tables', 'users', ['seat6'], ['id'])
    op.create_foreign_key('tables_seat7_fkey', 'tables', 'users', ['seat7'], ['id'])
    op.create_foreign_key('tables_seat2_fkey', 'tables', 'users', ['seat2'], ['id'])
    op.create_foreign_key('tables_seat3_fkey', 'tables', 'users', ['seat3'], ['id'])
    op.create_foreign_key('tables_seat8_fkey', 'tables', 'users', ['seat8'], ['id'])
    op.create_foreign_key('tables_seat1_fkey', 'tables', 'users', ['seat1'], ['id'])
    op.create_foreign_key('tables_seat5_fkey', 'tables', 'users', ['seat5'], ['id'])
    op.create_foreign_key('tables_seat9_fkey', 'tables', 'users', ['seat9'], ['id'])
    # ### end Alembic commands ###
