"""empty message

Revision ID: 29b107675925
Revises: 2fc007407414
Create Date: 2021-10-20 22:19:15.437961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b107675925'
down_revision = '2fc007407414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tables_seat_9_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat_10_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat_5_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat_7_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat_8_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat_6_fkey', 'tables', type_='foreignkey')
    op.drop_constraint('tables_seat_4_fkey', 'tables', type_='foreignkey')
    op.drop_column('tables', 'seat_7')
    op.drop_column('tables', 'seat_4')
    op.drop_column('tables', 'seat_10')
    op.drop_column('tables', 'seat_9')
    op.drop_column('tables', 'seat_5')
    op.drop_column('tables', 'seat_6')
    op.drop_column('tables', 'seat_8')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('seat_8', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat_6', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat_5', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat_9', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat_10', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat_4', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tables', sa.Column('seat_7', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tables_seat_4_fkey', 'tables', 'users', ['seat_4'], ['id'])
    op.create_foreign_key('tables_seat_6_fkey', 'tables', 'users', ['seat_6'], ['id'])
    op.create_foreign_key('tables_seat_8_fkey', 'tables', 'users', ['seat_8'], ['id'])
    op.create_foreign_key('tables_seat_7_fkey', 'tables', 'users', ['seat_7'], ['id'])
    op.create_foreign_key('tables_seat_5_fkey', 'tables', 'users', ['seat_5'], ['id'])
    op.create_foreign_key('tables_seat_10_fkey', 'tables', 'users', ['seat_10'], ['id'])
    op.create_foreign_key('tables_seat_9_fkey', 'tables', 'users', ['seat_9'], ['id'])
    # ### end Alembic commands ###
