"""empty message

Revision ID: 2fc007407414
Revises: ced04a462318
Create Date: 2021-10-20 22:08:10.308713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdc0a98111c'
down_revision = 'ced04a462318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('seat_3', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('seat_4', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('seat_5', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('seat_6', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('seat_7', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('seat_8', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('seat_9', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('seat_10', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tables', 'users', ['seat_6'], ['id'])
    op.create_foreign_key(None, 'tables', 'users', ['seat_7'], ['id'])
    op.create_foreign_key(None, 'tables', 'users', ['seat_9'], ['id'])
    op.create_foreign_key(None, 'tables', 'users', ['seat_4'], ['id'])
    op.create_foreign_key(None, 'tables', 'users', ['seat_5'], ['id'])
    op.create_foreign_key(None, 'tables', 'users', ['seat_8'], ['id'])
    op.create_foreign_key(None, 'tables', 'users', ['seat_10'], ['id'])
    op.create_foreign_key(None, 'tables', 'users', ['seat_3'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_column('tables', 'seat_10')
    op.drop_column('tables', 'seat_9')
    op.drop_column('tables', 'seat_8')
    op.drop_column('tables', 'seat_7')
    op.drop_column('tables', 'seat_6')
    op.drop_column('tables', 'seat_5')
    op.drop_column('tables', 'seat_4')
    op.drop_column('tables', 'seat_3')
    # ### end Alembic commands ###
