"""empty message

Revision ID: 352d31d31cd7
Revises: d88b7f0dc765
Create Date: 2021-10-21 13:49:49.301944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352d31d31cd7'
down_revision = 'd88b7f0dc765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'currentSimoleans',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'currentSimoleans',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
