"""empty message

Revision ID: 4725e2ed3526
Revises: 9161eb5b4b55
Create Date: 2021-10-20 22:31:54.590761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4725e2ed3526'
down_revision = '9161eb5b4b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'currentSimoleans',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'currentSimoleans',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
