"""empty message

Revision ID: 56e5d374c465
Revises: 8251440a7b80
Create Date: 2021-10-28 01:48:07.413248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e5d374c465'
down_revision = '8251440a7b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('commenter_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'users', ['commenter_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'commenter_user_id')
    # ### end Alembic commands ###
