"""empty message

Revision ID: ae03f32b3e1f
Revises: 352d31d31cd7
Create Date: 2021-10-21 14:24:38.069013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae03f32b3e1f'
down_revision = '352d31d31cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gametables', sa.Column('tableCreator', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'gametables', 'users', ['tableCreator'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gametables', type_='foreignkey')
    op.drop_column('gametables', 'tableCreator')
    # ### end Alembic commands ###
