"""empty message

Revision ID: c674d896674d
Revises: edadff0a67b9
Create Date: 2021-10-28 01:33:38.668402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c674d896674d'
down_revision = 'edadff0a67b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('commenter_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'users', ['commenter_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'commenter_user_id')
    # ### end Alembic commands ###
