"""empty message

Revision ID: c8bbd0ec8f02
Revises: 07302472424c
Create Date: 2021-10-28 02:05:21.695868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8bbd0ec8f02'
down_revision = '07302472424c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_owner_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_owner_id_fkey', 'comments', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
