"""empty message

Revision ID: ced04a462318
Revises: acf93e669c5a
Create Date: 2021-10-20 21:46:51.006967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced04a462318'
down_revision = 'acf93e669c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('seat_2', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tables', 'users', ['seat_2'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_column('tables', 'seat_2')
    # ### end Alembic commands ###
