"""empty message

Revision ID: edadff0a67b9
Revises: e78b3fd732bd
Create Date: 2021-10-26 07:56:05.400699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edadff0a67b9'
down_revision = 'e78b3fd732bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
